### ISSUE TITLE
Mysterious DE error

### ISSUE THREAD

**Issue by Munfred** [YosefLab/scvi-tools#1036]
Hello, I'm getting a cryptic DE error when trying to perform DE using masks for the group1 and group2 selections. I'm loading a model that was trained with scvi v0.8.1 but I have been able to perform DE with this model using different masks. There is something about the way I am constructing the mask which is causing the error, and I can't tell if it is my fault or something with scvi.

I created a notebook that reproduces the error, on the last cell -- you can ignore the convoluted way in which I'm constructing the mask:

https://colab.research.google.com/gist/Munfred/852bb634fab14c51a3a25edfa46144ee/scvi_de_error_2021-04-22.ipynb

I also copy the error output below in case you can tell from just looking at it
```
DE...:   0%|          | 0/1 [00:02<?, ?it/s]
ERROR:app:Exception on /submit [POST]
Traceback (most recent call last):
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_scvi_batch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/munfred/PycharmProjects/scdefg/scdefg/app.py", line 125, in receive_submission
    de = model.differential_expression( adata,
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/model/base/_rnamixin.py", line 202, in differential_expression
    result = _de_core(
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/model/base/_utils.py", line 149, in _de_core
    all_info = dc.get_bayes_factors(
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/utils/_differential.py", line 170, in get_bayes_factors
    scales_batches_1 = self.scale_sampler(
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/utils/_differential.py", line 393, in scale_sampler
    self.model_fn(self.adata, indices=idx, transform_batch=batch_idx)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/model/base/_rnamixin.py", line 87, in get_normalized_expression
    scdl = self._make_data_loader(
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/model/base/_base_model.py", line 115, in _make_data_loader
    dl = data_loader_class(
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/dataloaders/_ann_dataloader.py", line 134, in __init__
    self.dataset = AnnTorchDataset(adata, getitem_tensors=data_and_attributes)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/dataloaders/_anntorchdataset.py", line 29, in __init__
    self.setup_data_attr()
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/dataloaders/_anntorchdataset.py", line 42, in setup_data_attr
    self.data = {
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/dataloaders/_anntorchdataset.py", line 43, in <dictcomp>
    key: get_from_registry(self.adata, key)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/scvi/data/_anndata.py", line 71, in get_from_registry
    data = data.loc[:, attr_key]
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1060, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 807, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1124, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1073, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3724, in xs
    return self[key]
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/munfred/PycharmProjects/scdefg/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: '_scvi_batch'
INFO:werkzeug:127.0.0.1 - - [22/Apr/2021 15:34:33] "POST /submit HTTP/1.1" 500 -
```

**Comment by adamgayoso** [comment]
![Screen Shot 2021-04-22 at 4 08 06 PM](https://user-images.githubusercontent.com/10859440/115795536-f072d480-a384-11eb-8d47-a83be673ae58.png)

**Comment by Munfred** [comment]
Doink! Silly me - thanks!
