### ISSUE TITLE
Error when importing scvi (Dependencies)

### ISSUE THREAD

**Issue by khalilouardini** [YosefLab/scvi-tools#985]
I am trying to use scvi-tools with pytorch==1.7.1 to match my CUDA version (10.1), but I keep getting this Atrribute Error: 'torch.distributions.constraints' has no attribute '_CorrCholesky'
it seems like the Pyro api relies on the backend of a newer torch version. 

```pytb
Traceback (most recent call last):
  File "train_scvi.py", line 3, in <module>
    import scvi
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/scvi/__init__.py", line 10, in <module>
    from . import data, model, external
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/scvi/model/__init__.py", line 1, in <module>
    from ._autozi import AUTOZI
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/scvi/model/_autozi.py", line 12, in <module>
    from scvi.model.base import UnsupervisedTrainingMixin
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/scvi/model/base/__init__.py", line 1, in <module>
    from ._archesmixin import ArchesMixin
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/scvi/model/base/_archesmixin.py", line 11, in <module>
    from ._base_model import BaseModelClass
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/scvi/model/base/_base_model.py", line 9, in <module>
    import pyro
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/__init__.py", line 4, in <module>
    import pyro.poutine as poutine
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/poutine/__init__.py", line 4, in <module>
    from .handlers import (
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/poutine/handlers.py", line 60, in <module>
    from .collapse_messenger import CollapseMessenger
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/poutine/collapse_messenger.py", line 7, in <module>
    from pyro.distributions.distribution import COERCIONS
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/distributions/__init__.py", line 4, in <module>
    import pyro.distributions.torch_patch  # noqa F403
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/distributions/torch_patch.py", line 85, in <module>
    @patch_dependency('torch.distributions.constraints._CorrCholesky.check')
  File "/home/eecs/khalil.ouardini/miniconda3/envs/scvi-env/lib/python3.7/site-packages/pyro/distributions/torch_patch.py", line 18, in patch_dependency
    module = getattr(module, part)
AttributeError: module 'torch.distributions.constraints' has no attribute '_CorrCholesky'

```

#### Versions:

> 0.9.0

**Comment by adamgayoso** [comment]
It's pyro, for now you can install `pyro-ppl==1.5.2`. We'll push a solution soon

**Comment by adamgayoso** [comment]
@khalilouardini there's actually nothing we can do, it's the CUDA problems on the cluster, for now just downgrade Pyro. Thanks!
