### ISSUE TITLE
Specific GPU assignement

### ISSUE THREAD

**Issue by khalilouardini** [YosefLab/scvi-tools#994]
Specific gpu assignement fails

Code
```python
model = scvi.model.SCVI(adata)
model.train(n_epochs = 1, use_gpu = ["2"])
```

Error
```pytb
Traceback (most recent call last):
  File "train_scvi.py", line 47, in <module>
    model.train(n_epochs=2, use_gpu = ["2"])
  File "/home/eecs/khalil.ouardini/scvi-tools/scvi/model/base/_training_mixin.py", line 77, in train
    **trainer_kwargs,
  File "/home/eecs/khalil.ouardini/scvi-tools/scvi/train/_trainrunner.py", line 60, in __init__
    gpus, device = parse_use_gpu_arg(use_gpu)
  File "/home/eecs/khalil.ouardini/scvi-tools/scvi/model/_utils.py", line 49, in parse_use_gpu_arg
    return gpus, device
UnboundLocalError: local variable 'gpus' referenced before assignment
```

**Comment by adamgayoso** [comment]
Does just "2" work?

**Comment by khalilouardini** [comment]
No but passing an integer to torch.device works

**Comment by adamgayoso** [comment]
Would you like to fix it @khalilouardini ? We can discuss on slack what the intended behavior is.
